- app/customer/admin.py
- app/customer/apps.py
- app/customer/models.py
- app/customer/tests.py
- app/customer/views.py
- app/delivery_app/settings/base.py
- app/sajjang/models.py
> [ADD] customer 앱 추가

- app/customer/models.py
> [ADD] customer/models.py >> cart model 작성

- app/sajjang/models.py
> [ADD] Store 모델 추가 >> sajjang/models.py 에 Store 모델 추가

- app/sajjang/views.py
> [ADD] sajjang/views.py >> 뼈대 추가

- app/customer/views.py
- app/sajjang/models.py
[ADD] customer/views.py -> 각 url에 맞는 뷰 클래스 틀 작성
[REV] sajjang/models.py -> stores 모델 작성 완료로 인한 기존 주석 처리된 코드를 주석해제
[REV] sajjang/models.pt -> ERD에 맞춰 store 모델 이름을 stores 로 변경
> feat030 풀 리퀘스트 입니다.

- app/delivery_crew/models.py
[REV] delivery_crew/models.py -> DeliveryLocation FloatField 파라미터 삭제
파라미터 설정에 오류가 있어 docker-compose 테스트에 문제가 있었습니다.
해당 내용 수정입니다.
> feat033 풀 리퀘스트 입니다.

- app/customer/urls.py
> [ADD] urlpatterns 작성 >> customer urlpatters 작성

- app/customer/views.py
customer home, customer address view 작업
> [ADD] Customer view 작업  >> customer home, customer address view 작업

- app/sajjang/models.py
> [ADD] sajjang/models.py >> store_id, category_id에 null=True 적용

- app/sajjang/templates/home.html
> [ADD] sajjang home 템플릿 작성 >> sajjang home 템플릿 작성 (보완필요)

- app/customer/templates/orders/detail.html
- app/customer/views.py
- app/customer/webhook.py
[ADD] customer/view.py -> 결제 페이지 뷰 추가
[ADD] customer/webhook.py -> 결제 이후 처리 로직 추가
[ADD] customer/templates/orders/detail.html -> 주문 상세정보 템플릿
> 결제 기능 풀 리퀘스트 합니다.

- app/customer/templates/cart/list.html
- app/customer/templates/store/detail.html
- app/customer/templates/store/menu/detail.html
- app/customer/templates/store/menu/list.html
- app/customer/views.py
- app/delivery_app/settings/base.py
settings/base.py -> [ADD] 장고 템플릿 엔진의 1000 단위 , 찍기를 위한 기능 앱 추가
customer/
> views.py -> [REV] CustomerHomeView 의 View 클래스를 다시 TemplateView 로 변경, [ADD] CustomerCartView post 메소드 기능 추가
> templates/
>> store/detail.html -> [ADD] 템플릿 추가
>> store/menu/detail.html -> [ADD] 템플릿 추가
>> store/menu/list.html -> [ADD] 템플릿, 장바구니 제거, 수량변경 버튼 기능 추가
> 야간 작업 내용 풀리퀘스트 합니다.

- app/customer/templates/payment/cancle.html
- app/customer/templates/payment/complete.html
> [ADD] customer templates cancle.html, complete.html >> 돌아가기 버튼 추가

- app/customer/templates/cart/list.html
- app/customer/templates/orders/create.html
- app/customer/urls.py
- app/customer/views.py
[REV] 장바구니 목록을 조회할 때 가게별 주문하기 버튼을 넣었습니다.
주문 목록을 작성할때 전체를 가져오는것이 아닌 선택된 가게만 가져오도록 하였습니다.
> [REV] 장바구니 목록 수정

- app/customer/templates/orders/detail.html
- app/customer/templates/orders/list.html
- app/customer/views.py
customer/
> views.py -> [FIX] 주문내역, 상세보기 조회 뷰의 처리 로직 수정
> templates/orders/
>> detail.html -> [ADD] 주문 내역 상세보기 템플릿 추가
>> list.html -> [ADD] 주문 내역 리스트 템플릿 추가
> [feat054] 고객의 주문내역에 관한 템플릿 작업입니다.

- app/customer/templates/address/detail.html
- app/customer/templates/orders/create.html
- app/customer/views.py
* customer/ 
+ views.py 
- [FIX] CustomerOrderCreateView get함수 재작성 
- [FIX] CustomerPaymentView 가게 필터를 통해 주문하고자 하는 가게만 결제 되도록 수정 
+ templates/ 
- address/detail.html -> [FIX] {{ block.super }} 오타 수정 
- orders/create.html -> [FIX] 버튼 활성화, 뷰 클래스 재작성으로 인한 변수명 수정
> [feat066] 주문 작성 -> 결제 까지의 보완점 개선사항입니다.

- app/account/models.py
- app/customer/models.py
- app/delivery_crew/models.py
- app/sajjang/models.py
> [feat069] DB 컬럼명 지정입니다.

- app/delivery_crew/templates/history.html
> [ADD] template 수정 >> button 위치 수정

- app/delivery_crew/templates/del_crew_base.html
- app/delivery_crew/templates/history.html
- app/delivery_crew/templates/history_detail.html
- app/delivery_crew/views.py
views.py -> [ADD] api를 호출하여 해당 주소의 좌표값을 가져오는 기능 추가 
history_detail.html -> [ADD] 경로안내 지도 추가
다음 작업
1. 배달크루의 위치 모델 변경
2. 더미데이터 추가
3. 경로안내에 고정된 출발지 -> 배달크루의 위치 적용
> [feat070] T Map API 를 사용하여 고정된 출발지 ~ 고객의 주소 까지의 경로 안내 기능 작성

- app/delivery_crew/templates/del_crew_base.html
- app/delivery_crew/templates/history.html
- app/delivery_crew/templates/history_detail.html
- app/delivery_crew/views.py
views.py -> [ADD] api를 호출하여 해당 주소의 좌표값을 가져오는 기능 추가
history_detail.html -> [ADD] 경로안내 지도 추가
다음 작업
1. 배달크루의 위치 모델 변경
2. 더미데이터 추가
3. 경로안내에 고정된 출발지 -> 배달크루의 위치 적용
> [feat076] T Map API 객제 생성, 고정된 시작지 -> 고객 주소 까지의 경로 안내

- app/account/management/commands/create_dummy_data.py
- app/delivery_crew/models.py
- app/delivery_crew/templates/history_detail.html
- app/delivery_crew/views.py
create_dummy_data.py -> [ADD] 배달원 위치 정보 입력 코드 작성
models.py -> [REV] 배달원 위치정보 저장방식 변경 (좌표-> 주소)
views.py -> [FIX] 배달원의 활동영역에 따른 주문 리스트 조회
history_detail.html -> [FIX] 배달원 위치와 고객의 주소의 경로 안내 제공
> 배달원 모델수정, 배달원의 위치 정보 더미데이터 작성, 배달원 위치와 고객 주소의 경로안내 제공

- app/delivery_crew/templates/history_detail.html
histoery_detail.html -> [ADD] 경로 안내 그리기가 완료되면 해당 구역으로 지도의 보기좌표, 줌 레벨 조정
> 경로 안내 시작시 지도 자동이동 구현입니다.

- app/account/management/commands/create_dummy_data.py
- app/delivery_crew/templates/history_detail.html
- app/delivery_crew/views.py
create_dummy_data 의 불필요한 print문 삭제
> [feat090] 경로 안내 시작점을 배달크루의 위치 -> 가게의 위치로 수정
